## Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np

In [ ]:
x = np.array([2, 3, 4])
y = np.array([7, 8, 9])
# x + y

array([ 9, 11, 13])

In [6]:
xy = np.add(x, y)
xy

array([ 9, 11, 13])

### Slow: Using Python Loops instead of vectorization

In [8]:
x = [2, 3, 4]
y = [7, 8, 9]
x + y

[2, 3, 4, 7, 8, 9]

In [10]:
z = []
for i in range(len(x)):
    z.append(x[i]+y[i])
z

[9, 11, 13]

In [11]:
# define two sample arrays
a = np.array([10, 20, 30])
b = np.array([3, 4, 5])



In [ ]:
# addition of two arrays
c = np.add(a, b)
c
# alternative
# c = a + b

array([13, 24, 35])

In [15]:
# subtraction of two arrays
d = np.subtract(a, b)
d
# alternative
# d = a - b

array([ 7, 16, 25])

In [17]:
# multiplication of two arrays
e = np.multiply(a, b)
e
# alternative
# e = a * b

array([ 30,  80, 150])

In [19]:
# division of two arrays
f = np.divide(a, b)
f
# alternative
# f = a / b

array([3.33333333, 5.        , 6.        ])

In [ ]:
# floor division of two arrays
g = np.floor_divide(a, b)
g
# alternative
# g = a // b

array([3, 5, 6])

In [21]:
# unary operations on arrays
h = np.negative(a)
h

array([-10, -20, -30])