## Computation on NumPy Arrays: Universal Functions

In [1]:
import numpy as np

In [ ]:
x = np.array([2, 3, 4])
y = np.array([7, 8, 9])
# x + y

array([ 9, 11, 13])

In [6]:
xy = np.add(x, y)
xy

array([ 9, 11, 13])

### Slow: Using Python Loops instead of vectorization

In [8]:
x = [2, 3, 4]
y = [7, 8, 9]
x + y

[2, 3, 4, 7, 8, 9]

In [10]:
z = []
for i in range(len(x)):
    z.append(x[i]+y[i])
z

[9, 11, 13]

In [11]:
# define two sample arrays
a = np.array([10, 20, 30])
b = np.array([3, 4, 5])



In [ ]:
# addition of two arrays
c = np.add(a, b)
c
# alternative
# c = a + b

array([13, 24, 35])

In [15]:
# subtraction of two arrays
d = np.subtract(a, b)
d
# alternative
# d = a - b

array([ 7, 16, 25])

In [17]:
# multiplication of two arrays
e = np.multiply(a, b)
e
# alternative
# e = a * b

array([ 30,  80, 150])

In [19]:
# division of two arrays
f = np.divide(a, b)
f
# alternative
# f = a / b

array([3.33333333, 5.        , 6.        ])

In [ ]:
# floor division of two arrays
g = np.floor_divide(a, b)
g
# alternative
# g = a // b

array([3, 5, 6])

In [22]:
# unary operations on arrays
h = np.negative(a)
h
# alternative
# h = -a

array([-10, -20, -30])

In [ ]:
# power of two arrays
i = np.power(a, b)
i
# alternative
# i = a ** b

array([100, 400, 900])

In [ ]:
# modulus of two arrays
j = np.mod(a, b)
j
# alternative
# j = a % b

array([1, 0, 0])

## Aggregation in Numpy

### Summing the values in an array

In [27]:
R = np.arange(1, 11)
R

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
sum_R = sum(R)
sum_R
# alternative
# sum_R = np.sum(R)

np.int64(55)

In [43]:
R2 = np.random.random(100)
R2

array([0.11255561, 0.80167711, 0.3766701 , 0.54635037, 0.82852919,
       0.20042147, 0.20693145, 0.51544841, 0.02716303, 0.66654805,
       0.7046431 , 0.38356007, 0.13551658, 0.92539708, 0.54929511,
       0.08940043, 0.04041616, 0.57308252, 0.63685673, 0.44137717,
       0.29127393, 0.49350571, 0.27819776, 0.71150644, 0.17414409,
       0.31310486, 0.36160045, 0.15691324, 0.08517044, 0.16383699,
       0.10883758, 0.27273738, 0.07686863, 0.16727034, 0.81032111,
       0.70242168, 0.39615529, 0.06098265, 0.20850292, 0.04221942,
       0.92457032, 0.12838502, 0.07478482, 0.23949734, 0.68387589,
       0.98603384, 0.42343507, 0.16861854, 0.12720534, 0.01749711,
       0.45768716, 0.34722   , 0.05758681, 0.42937365, 0.29779599,
       0.31846178, 0.12125307, 0.71477865, 0.4468102 , 0.63743124,
       0.98501616, 0.70694469, 0.71858064, 0.30726224, 0.55812684,
       0.65659751, 0.99541897, 0.70732039, 0.9292427 , 0.59433237,
       0.25029465, 0.49086363, 0.65431813, 0.73948919, 0.58207

In [46]:
# using python sum function
sum_R2 = sum(R2)
sum_R2

np.float64(44.4379440655254)

In [47]:
# using numpy to sum the values in an array
sum_R2 = np.sum(R2)
sum_R2

np.float64(44.43794406552538)

In [49]:
%timeit sum(R2)

7.98 μs ± 585 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [50]:
%timeit np.sum(R2)

1.8 μs ± 523 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [51]:
R3 = np.random.random(1000000)
R3

array([0.29625727, 0.4212166 , 0.03760299, ..., 0.93555548, 0.92889885,
       0.40386194], shape=(1000000,))

In [53]:
%timeit np.sum(R3)

296 μs ± 71.9 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [54]:
%timeit sum(R3)

71.3 ms ± 9.29 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [55]:
%timeit np.max(R3)

299 μs ± 112 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [56]:
%timeit max(R3)

49.1 ms ± 1.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


### Multi dimensional Aggregates

In [57]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [58]:
M.sum()

np.int64(45)

In [61]:
M.sum(axis=0)  # sum of each column
# M.sum(axis=1)  # sum of each row

array([12, 15, 18])

## Broadcasting in NumPy

In [63]:
# adding a scalar to an array
a = np.array([1, 2, 3])
b = 5
c = a + b
c

array([6, 7, 8])

In [67]:
# add 1D to a 2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print('a:', a)
print('a shape:', a.shape)
b = np.array([10, 20, 30])
print('b:', b)
print('b shape:', b.shape)
c = a + b
print('c:', c)
print('c shape:', c.shape)

a: [[1 2 3]
 [4 5 6]]
a shape: (2, 3)
b: [10 20 30]
b shape: (3,)
c: [[11 22 33]
 [14 25 36]]
c shape: (2, 3)


In [72]:
a = np.arange(3).reshape(3, 1)
b = np.arange(3)
print('Shape A:', a.shape)
print('Shape B:', b.shape)
c = a + b
print('Shape C:', c.shape)

Shape A: (3, 1)
Shape B: (3,)
Shape C: (3, 3)


In [73]:
print(c)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


In [75]:
# arrays that are not compatible for broadcasting
M = np.array((3, 2), dtype=int)
a = np.arange(3)
# a + M

In [80]:
# more examples of arrays that are not compatible for broadcasting
a = np.arange(3).reshape(3, 1)
print('Shape A:', a.shape)
b= np.zeros((2, 2))
print('Shape B:', b.shape)
# a + b

Shape A: (3, 1)
Shape B: (2, 2)


## Boolean Masking

In [84]:
arr = np.array([10, 20, 30, 40, 50])

# create the mask
mask = arr > 25

# using the mask
result = arr[mask]
print('Array:', arr)
print('Mask:', mask)
print('Result:', result)

Array: [10 20 30 40 50]
Mask: [False False  True  True  True]
Result: [30 40 50]


In [85]:
arr = np.arange(1, 11)
mask = arr > 5
result = arr[mask]
print('Array:', arr)
print('Mask:', mask)
print('Result:', result)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Mask: [False False False False False  True  True  True  True  True]
Result: [ 6  7  8  9 10]


### Boolean masking with 2D arrays

In [86]:
arr2D = np.arange(1, 10).reshape(3, 3)
print('2D Array:\n', arr2D)

2D Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [87]:
# get all elements greater than 5
mask2D = arr2D > 5
print('Mask 2D:\n', mask2D)

Mask 2D:
 [[False False False]
 [False False  True]
 [ True  True  True]]


In [88]:
result = arr2D[mask2D]
print('Result:\n', result)

Result:
 [6 7 8 9]


In [90]:
arr2D[arr2D > 5] = 0
print('2D Array:\n', arr2D)

2D Array:
 [[1 2 3]
 [4 5 0]
 [0 0 0]]


## Comparison Operators in NumPy

In [91]:
x = np.arange(1, 6)
x

array([1, 2, 3, 4, 5])

In [94]:
print(x>3)
print(x<3)
print(x==3)

[False False False  True  True]
[ True  True False False False]
[False False  True False False]


In [95]:
2 * x

array([ 2,  4,  6,  8, 10])

In [96]:
x ** 2

array([ 1,  4,  9, 16, 25])

In [97]:
(2 * x) == (x ** 2)

array([False,  True, False, False, False])

## Counting Entries

In [106]:
# check how many values are gonna be less than 6
x = np.random.randint(1, 13, size=12).reshape(3, 4)
print('Array:', x)
mask = x < 6
print('Mask:', mask)
nz = np.count_nonzero(x < 6)
print('Number of values less than 6:', nz)

Array: [[10  1  6  1]
 [ 2 10  3 10]
 [ 9  6 12  6]]
Mask: [[False  True False  True]
 [ True False  True False]
 [False False False False]]
Number of values less than 6: 4


In [107]:
# sum of the elements less than 7
sum_mask = x < 7
np.sum(sum_mask)

np.int64(7)

In [108]:
x

array([[10,  1,  6,  1],
       [ 2, 10,  3, 10],
       [ 9,  6, 12,  6]])

In [109]:
np.sum(mask, axis=0)

array([1, 1, 1, 1])

In [110]:
np.any(x > 8)

np.True_

In [111]:
np.all(x > 8)

np.False_

### Boolean Operators

In [112]:
y = np.array([10, 15, 20, 25, 30])
print('Array:', y)

Array: [10 15 20 25 30]


In [123]:
z = y < 15
print('Mask:', z)

Mask: [ True False False False False]


In [124]:
w = y > 25
print('Mask:', w)

Mask: [False False False False  True]


In [125]:
mask = z | w 
print('Mask:', mask)

Mask: [ True False False False  True]


In [121]:
result = y[mask]
print('Result:', result)

Result: [20 25]


In [126]:
v = ~(y > 20)
print("V:", v)

V: [ True  True  True False False]


In [127]:
result_not = y[v]
print('Result Not:', result_not)

Result Not: [10 15 20]


## Fancy Indexing

### Indexing with a List of Indices

In [130]:
F = np.random.randint(1, 50, size=(5,))
F

array([ 3, 42, 30,  3,  8])

In [134]:
F[0:3]

array([ 3, 42, 30])