In [3]:
x = 4
# x = 'four'
x 

4

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# list of strings
L2 = ['a', 'b', 'c', 'd']
L2

['a', 'b', 'c', 'd']

In [6]:
type(L2[0])

str

In [7]:
# mixed list of values
L3 = [1, 'a', 3.14, True]
L3 

[1, 'a', 3.14, True]

In [8]:
[type(item) for item in L3]

[int, str, float, bool]

## Fixed-Type Arrays

In [9]:
import array as arr

In [10]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
A = arr.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from python lists

In [13]:
# import the library
import numpy as np

In [15]:
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
# 2 dimensional array
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])