In [3]:
x = 4
# x = 'four'
x 

4

In [4]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
# list of strings
L2 = ['a', 'b', 'c', 'd']
L2

['a', 'b', 'c', 'd']

In [6]:
type(L2[0])

str

In [7]:
# mixed list of values
L3 = [1, 'a', 3.14, True]
L3 

[1, 'a', 3.14, True]

In [8]:
[type(item) for item in L3]

[int, str, float, bool]

## Fixed-Type Arrays

In [9]:
import array as arr

In [10]:
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [12]:
A = arr.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

### Creating Arrays from python lists

In [13]:
# import the library
import numpy as np

In [15]:
np.array(L)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [18]:
np.array([1,2,3,4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [20]:
# 2 dimensional array
np.array([[1,2,3], [4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

## 1D Array

In [22]:
a = np.array([1,2,3])
a

array([1, 2, 3])

## 2D Array

In [23]:
b = np.array([[1,2,3], [4,5,6]])
b.shape

(2, 3)

## 3D Array

In [26]:
c = np.array([[
        [1,2,3], 
        [4,5,6], 
        [7,8,9]
    ]])
c.shape

(1, 3, 3)

In [27]:
d = np.array([[[1,3], [3,4]], [[5,6], [7,8]]])
d.shape

(2, 2, 2)

## Creating Arrays from Scratch

In [28]:
# create an arary of zeros
np.zeros(5, dtype='int')

array([0, 0, 0, 0, 0])

In [30]:
# create a 3x5 filled in with ones
np.ones((3,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# create a 3x5 filled with 3.14
np.full((3,5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [32]:
# create an aray fiiled in with a linear sequence
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [33]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [34]:
# create a 3x3 array of uniformly distributed random values between 0 and 1
np.random.random((3,3))

array([[0.72046552, 0.08364426, 0.41827564],
       [0.4223079 , 0.19061724, 0.42023169],
       [0.28474948, 0.31883769, 0.75548359]])

In [36]:
# create a 3x3 array of nomarlly distributed random values with mean 0 and standard deviation 1
np.random.normal(0, 1, (3,3))

array([[-0.36338396,  0.08822855,  1.14913703],
       [ 0.12759693,  0.49934719, -0.92775768],
       [-0.61722678, -2.26729293,  0.94202723]])

In [37]:
# create a 3x3 array of random integers between 0 and 10
np.random.randint(0, 10, (3,3))

array([[8, 3, 0],
       [8, 6, 5],
       [6, 8, 2]])

In [38]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [40]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that memory location
np.empty(3, dtype='int')

array([4607182418800017408, 4607182418800017408, 4607182418800017408])

## Data Manipulation

### NumPy Array Attributes

In [48]:
np.random.seed(42) # set the random seed for reproducibility

# create a one-dimensional array
x1 = np.random.randint(10, size=6)
x1

# create a two-dimensional array
x2 = np.random.randint(10, size=(3,4))
x2

# create a three-dimensional array
x3 = np.random.randint(10, size=(3,4,5))
x3

array([[[5, 1, 4, 0, 9],
        [5, 8, 0, 9, 2],
        [6, 3, 8, 2, 4],
        [2, 6, 4, 8, 6]],

       [[1, 3, 8, 1, 9],
        [8, 9, 4, 1, 3],
        [6, 7, 2, 0, 3],
        [1, 7, 3, 1, 5]],

       [[5, 9, 3, 5, 1],
        [9, 1, 9, 3, 7],
        [6, 8, 7, 4, 1],
        [4, 7, 9, 8, 8]]])

In [49]:
print("x1:", x1)
print("x2: ", x2)
print("x3:", x3)

x1: [6 3 7 4 6 9]
x2:  [[2 6 7 4]
 [3 7 7 2]
 [5 4 1 7]]
x3: [[[5 1 4 0 9]
  [5 8 0 9 2]
  [6 3 8 2 4]
  [2 6 4 8 6]]

 [[1 3 8 1 9]
  [8 9 4 1 3]
  [6 7 2 0 3]
  [1 7 3 1 5]]

 [[5 9 3 5 1]
  [9 1 9 3 7]
  [6 8 7 4 1]
  [4 7 9 8 8]]]


In [50]:
print("x1 shape:", x1.shape)
print("x2 shape:", x2.shape)
print("x3 shape:", x3.shape)

x1 shape: (6,)
x2 shape: (3, 4)
x3 shape: (3, 4, 5)


In [51]:
print("x1 ndim: ", x1.ndim)
print("x2 ndim: ", x2.ndim)
print("x3 ndim: ", x3.ndim)

x1 ndim:  1
x2 ndim:  2
x3 ndim:  3


In [52]:
print('x1 size: ', x1.size, 'bytes')
print('x2 size: ', x2.size, 'bytes')
print('x3 size: ', x3.size, 'bytes')

x1 size:  6 bytes
x2 size:  12 bytes
x3 size:  60 bytes


In [53]:
print('x1 dtype: ', x1.dtype)
print('x2 dtype: ', x2.dtype)
print('x3 dtype: ', x3.dtype)

x1 dtype:  int64
x2 dtype:  int64
x3 dtype:  int64


## Accessing items in arrays

In [56]:
x1

array([6, 3, 7, 4, 6, 9])

In [57]:
x1[3]

np.int64(4)

In [54]:
x2

array([[2, 6, 7, 4],
       [3, 7, 7, 2],
       [5, 4, 1, 7]])

In [55]:
x2[2,0]

np.int64(5)

In [58]:
x2[:,3] # all rows, column 3

array([4, 2, 7])

In [59]:
#  row 2, all columns
x2[1,:]

array([3, 7, 7, 2])

In [ ]:
x2[:, 1:3] # all rows, columns 1 and 2

array([[6, 7],
       [7, 7],
       [4, 1]])

In [ ]:
x2[0:2] # rows 0 and 1, all columns

array([[2, 6, 7, 4],
       [3, 7, 7, 2]])

In [64]:
# split the columns
x2[0:2, 1:3] # rows 0 and 1, columns 0 and 1

array([[6, 7],
       [7, 7]])

In [68]:
x2[2:, 2:] # rows 2 and beyond, columns 2 and beyond

array([[1, 7]])

In [70]:
t = x2[1,2]
t

np.int64(7)

In [71]:
x2[1,2] =55

In [72]:
x2

array([[ 2,  6,  7,  4],
       [ 3,  7, 55,  2],
       [ 5,  4,  1,  7]])

In [73]:
x

4

### Sub arrays no-copy views

In [74]:
print(x2)

[[ 2  6  7  4]
 [ 3  7 55  2]
 [ 5  4  1  7]]


In [75]:
x2[0,0] = 43

In [76]:
print(x2)

[[43  6  7  4]
 [ 3  7 55  2]
 [ 5  4  1  7]]


In [79]:
sub_array = x2[1:3, 0:2]
sub_array

array([[3, 7],
       [5, 4]])

In [80]:
sub_array[0,0] = 99
print(sub_array)

[[99  7]
 [ 5  4]]


In [81]:
sub_array[1,0] = 67
print(sub_array)

[[99  7]
 [67  4]]


In [82]:
x2

array([[43,  6,  7,  4],
       [99,  7, 55,  2],
       [67,  4,  1,  7]])

In [83]:
copy = x2.copy()
copy[0,0] = 88
print(copy)

[[88  6  7  4]
 [99  7 55  2]
 [67  4  1  7]]


In [84]:
x2

array([[43,  6,  7,  4],
       [99,  7, 55,  2],
       [67,  4,  1,  7]])