# Numpy Exercise 1

### All of the questions in this exercise are attributed to rougier/numpy-100

In [7]:
pip install --upgrade numpy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 636.8 kB/s  0:00:081.6 kB/s eta 0:00:01:03
  Attempting uninstall: numpy
    Found existing installation: numpy 2.3.4
    Uninstalling numpy-2.3.4:
      Successfully uninstalled numpy-2.3.4
Note: you may need to restart the kernel to use updated packages.


#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [10]:
print("NumPy version:", np.__version__)
print("\nNumPy configuration:")
np.show_config()

NumPy version: 2.3.4

NumPy configuration:
Build Dependencies:
  blas:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
  lapack:
    detection method: system
    found: true
    include directory: unknown
    lib directory: unknown
    name: accelerate
    openblas configuration: unknown
    pc file directory: unknown
    version: unknown
Compilers:
  c:
    commands: cc
    linker: ld64
    name: clang
    version: 15.0.0
  c++:
    commands: c++
    linker: ld64
    name: clang
    version: 15.0.0
  cython:
    commands: cython
    linker: cython
    name: cython
    version: 3.1.4
Machine Information:
  build:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
  host:
    cpu: aarch64
    endian: little
    family: aarch64
    system: darwin
Python Information:
  path: /private/var/folders/y6/nj790

#### 3. Create a null vector of size 10 (★☆☆)

In [11]:
null_vector = np.zeros(10)
print("Null vector:", null_vector)

Null vector: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [12]:
arr = np.array([1, 2, 3, 4, 5])
memory_size = arr.size * arr.itemsize
print(f"Memory size of array: {memory_size} bytes")

Memory size of array: 40 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [13]:
print("\nDocumentation for np.add:")
np.info(np.add)


Documentation for np.add:
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via th

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [14]:
null_vector_fifth = np.zeros(10)
null_vector_fifth[4] = 1  # index 4 is the 5th element
print("Null vector with fifth element = 1:", null_vector_fifth)

Null vector with fifth element = 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [15]:
vector_range = np.arange(10, 50)
print("Vector from 10 to 49:", vector_range)

Vector from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [16]:
vector = np.arange(10, 20)
reversed_vector = vector[::-1]
print("Original vector:", vector)
print("Reversed vector:", reversed_vector)

Original vector: [10 11 12 13 14 15 16 17 18 19]
Reversed vector: [19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [18]:
matrix_3x3 = np.arange(9).reshape(3, 3)
print(matrix_3x3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [19]:
arr = np.array([1, 2, 0, 0, 4, 0])
non_zero_indices = np.nonzero(arr)
print("Array:", arr)
print("Indices of non-zero elements:", non_zero_indices[0])

Array: [1 2 0 0 4 0]
Indices of non-zero elements: [0 1 4]


#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
random_3d = np.random.random((3, 3, 3))
print(random_3d)

[[[0.21584771 0.6197128  0.73780101]
  [0.33780184 0.47865462 0.53487155]
  [0.14295009 0.57879498 0.2258725 ]]

 [[0.5917232  0.7970286  0.60825062]
  [0.21811399 0.80898349 0.18746516]
  [0.09911539 0.13809368 0.27803794]]

 [[0.70643431 0.11530147 0.16630033]
  [0.40835872 0.87667992 0.72831447]
  [0.51157647 0.83820273 0.93620571]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [7]:
np.random.seed(42) 
random_10x10 = np.random.random((10, 10))
min_value = random_10x10.min()
max_value = random_10x10.max()
print("10x10 random array:")
print(random_10x10)
print(f"Minimum value: {min_value}")
print(f"Maximum value: {max_value}")

10x10 random array:
[[0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
  0.05808361 0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264 0.21233911 0.18182497 0.18340451
  0.30424224 0.52475643 0.43194502 0.29122914]
 [0.61185289 0.13949386 0.29214465 0.36636184 0.45606998 0.78517596
  0.19967378 0.51423444 0.59241457 0.04645041]
 [0.60754485 0.17052412 0.06505159 0.94888554 0.96563203 0.80839735
  0.30461377 0.09767211 0.68423303 0.44015249]
 [0.12203823 0.49517691 0.03438852 0.9093204  0.25877998 0.66252228
  0.31171108 0.52006802 0.54671028 0.18485446]
 [0.96958463 0.77513282 0.93949894 0.89482735 0.59789998 0.92187424
  0.0884925  0.19598286 0.04522729 0.32533033]
 [0.38867729 0.27134903 0.82873751 0.35675333 0.28093451 0.54269608
  0.14092422 0.80219698 0.07455064 0.98688694]
 [0.77224477 0.19871568 0.00552212 0.81546143 0.70685734 0.72900717
  0.77127035 0.07404465 0.35846573 0.11586906]
 [0.86310343 0.62329813 0.33089802 0.06355835 0.31098232 0.3

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [11]:
np.random.seed(42)
random_vector_30 = np.random.random(30)
mean_value = random_vector_30.mean()
print("Random vector of size 30:", random_vector_30)
print(f"Mean value: {mean_value}")

Random vector of size 30: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864 0.15599452
 0.05808361 0.86617615 0.60111501 0.70807258 0.02058449 0.96990985
 0.83244264 0.21233911 0.18182497 0.18340451 0.30424224 0.52475643
 0.43194502 0.29122914 0.61185289 0.13949386 0.29214465 0.36636184
 0.45606998 0.78517596 0.19967378 0.51423444 0.59241457 0.04645041]
Mean value: 0.43859727209743676


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [12]:
border_array = np.ones((5, 5))
border_array[1:-1, 1:-1] = 0
print("2D array with 1 on border and 0 inside:")
print(border_array)

2D array with 1 on border and 0 inside:
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
