# Numpy Exercise 5

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 61. Find the nearest value from a given value in an array (★★☆)

In [3]:
def find_nearest(arr, value):
    idx = np.abs(arr - value).argmin()
    return arr[idx], idx

arr = np.array([1, 3, 7, 9, 12, 15, 20])
value = 10

nearest, idx = find_nearest(arr, value)
print(f"Array: {arr}")
print(f"Value: {value}")
print(f"Nearest value: {nearest} at index {idx}")

Array: [ 1  3  7  9 12 15 20]
Value: 10
Nearest value: 9 at index 3


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [7]:
A = np.array([[1, 2, 3]]) 
B = np.array([[4], [5], [6]])

print("A shape:", A.shape)
print("A:")
print(A)
print("\nB shape:", B.shape)
print("B:")
print(B)

# Using broadcasting
result_broadcast = A + B
print("Broadcasting result:")
print(result_broadcast)
print("Shape:", result_broadcast.shape)

A shape: (1, 3)
A:
[[1 2 3]]

B shape: (3, 1)
B:
[[4]
 [5]
 [6]]
Broadcasting result:
[[5 6 7]
 [6 7 8]
 [7 8 9]]
Shape: (3, 3)


#### 63. Create an array class that has a name attribute (★★☆)

In [8]:
class NamedArray(np.ndarray):    
    def __new__(cls, input_array, name="unnamed"):
        obj = np.asarray(input_array).view(cls)
        obj.name = name
        return obj
    
    def __array_finalize__(self, obj):
        if obj is None:
            return
        self.name = getattr(obj, 'name', "unnamed")
    
    def __repr__(self):
        return f"{super().__repr__()}\nName: {self.name}"

# Create named arrays
arr1 = NamedArray([1, 2, 3, 4], "my_array")
print(arr1)

arr2 = NamedArray(np.random.rand(3, 3), "random_matrix")
print("\n", arr2)

# Operations preserve name
arr3 = arr1 + 5
print("\nAfter operation:")
print(arr3)

# Slicing preserves name
arr4 = arr2[0:2, 0:2]
print("\nAfter slicing:")
print(arr4)

[1 2 3 4]

 [[0.40596165 0.88697537 0.24264395]
 [0.0245935  0.0054024  0.76059665]
 [0.67305134 0.08389741 0.4361833 ]]

After operation:
[6 7 8 9]

After slicing:
[[0.40596165 0.88697537]
 [0.0245935  0.0054024 ]]


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [9]:
def add_to_indices(vector, indices):
    result = vector.copy()
    np.add.at(result, indices, 1)
    return result

v = np.array([0, 0, 0, 0, 0])
idx = np.array([0, 1, 2, 1, 0, 3])

print("Original vector:", v)
print("Indices:", idx)
result = add_to_indices(v, idx)
print("After adding 1:", result)

v2 = np.array([0, 0, 0, 0, 0])
v2[idx] += 1 
print("\nWithout handling repeats:", v2)

def add_to_indices_multiple(vector, indices, increments):
    result = vector.copy()
    np.add.at(result, indices, increments)
    return result

v3 = np.array([0, 0, 0, 0, 0])
idx3 = np.array([0, 1, 2, 1, 0, 3])
inc = np.array([1, 2, 3, 4, 5, 6])
result3 = add_to_indices_multiple(v3, idx3, inc)
print(f"\nWith different increments {inc}:")
print("Result:", result3)

Original vector: [0 0 0 0 0]
Indices: [0 1 2 1 0 3]
After adding 1: [2 2 1 1 0]

Without handling repeats: [1 1 1 1 0]

With different increments [1 2 3 4 5 6]:
Result: [6 6 3 6 0]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [10]:
def accumulate_to_F(X, I, F=None):
    """Accumulate X elements into F using indices I."""
    if F is None:
        F = np.zeros(max(I) + 1, dtype=X.dtype)
    
    # Use np.add.at for accumulation with repeated indices
    np.add.at(F, I, X)
    return F

X = np.array([1, 2, 3, 4, 5])
I = np.array([0, 1, 0, 2, 1])  # indices

print("X:", X)
print("I:", I)

F = accumulate_to_F(X, I)
print("F:", F)

# Equivalent to:
print("\nAlternative using loop:")
F2 = np.zeros(3)
for i, x in zip(I, X):
    F2[i] += x
print("F2:", F2)

# With pre-allocated F
F_preallocated = np.array([10, 20, 30])
F3 = accumulate_to_F(X, I, F_preallocated)
print("\nWith pre-allocated F:", F3)

X: [1 2 3 4 5]
I: [0 1 0 2 1]
F: [4 7 4]

Alternative using loop:
F2: [4. 7. 4.]

With pre-allocated F: [14 27 34]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [12]:
def count_unique_colors(image):
    """Count unique colors in an RGB image."""
    # Reshape image to (N, 3) where N = w * h
    h, w, channels = image.shape
    pixels = image.reshape(-1, channels)
    unique_colors = np.unique(pixels, axis=0)
    return len(unique_colors), unique_colors

# Create sample image with unique colors
image = np.random.randint(0, 256, size=(10, 10, 3), dtype=np.uint8)
unique_count, unique_colors = count_unique_colors(image)
print(f"Image shape: {image.shape}")
print(f"Number of unique colors: {unique_count}")
print(f"First 5 unique colors:\n{unique_colors[:5]}")

# With limited colors
image_limited = np.zeros((10, 10, 3), dtype=np.uint8)
image_limited[0, 0] = [255, 0, 0]
image_limited[0, 1] = [0, 255, 0]
image_limited[0, 2] = [0, 0, 255]
image_limited[1, 0] = [255, 0, 0]  # Repeat color
unique_count2, unique_colors2 = count_unique_colors(image_limited)
print(f"\nLimited image unique colors: {unique_count2}")
print("Unique colors:", unique_colors2)

Image shape: (10, 10, 3)
Number of unique colors: 100
First 5 unique colors:
[[  7 221 243]
 [  7 246 213]
 [  8 238 167]
 [ 12 132  44]
 [ 15 227 141]]

Limited image unique colors: 4
Unique colors: [[  0   0   0]
 [  0   0 255]
 [  0 255   0]
 [255   0   0]]


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [13]:
def sum_last_two_axes(arr):
    """Sum over the last two axes of a 4D array."""
    return np.sum(arr, axis=(-2, -1))

# Create 4D array
arr4d = np.random.rand(2, 3, 4, 5)
print("Array shape:", arr4d.shape)

# Sum over last two axes
result = sum_last_two_axes(arr4d)
print("Result shape:", result.shape)  # Should be (2, 3)
print("Result:", result)

Array shape: (2, 3, 4, 5)
Result shape: (2, 3)
Result: [[12.54264258  9.80566011 11.94658632]
 [10.09482193 10.81491631 11.48222873]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [ ]:
def subset_means(D, S):
    unique_indices = np.unique(S)
    means = np.zeros(len(unique_indices))
    
    for i, idx in enumerate(unique_indices):
        means[i] = np.mean(D[S == idx])
    
    return means, unique_indices

# Example
D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
S = np.array([0, 1, 0, 1, 0, 2, 2, 0, 1, 2])

print("Data D:", D)
print("Subset indices S:", S)

means, indices = subset_means(D, S)
print("Means:", means)
print("Indices:", indices)

Data D: [ 1  2  3  4  5  6  7  8  9 10]
Subset indices S: [0 1 0 1 0 2 2 0 1 2]
Means: [4.25       5.         7.66666667]
Indices: [0 1 2]


#### 69. How to get the diagonal of a dot product? (★★★)

In [19]:
def diagonal_of_dot(A, B):
    full_dot = A @ B
    diag1 = np.diag(full_dot)
    
    return diag1

# Example with square matrices
A = np.random.rand(5, 5)
B = np.random.rand(5, 5)

diag1 = diagonal_of_dot(A, B)
print("A.shape:", A.shape)
print("B.shape:", B.shape)
print("Diagonal from full dot:", diag1)

# Example with non-square matrices
A = np.random.rand(5, 3)
B = np.random.rand(3, 5)
diag1 = diagonal_of_dot(A, B)
print("\nNon-square matrices:")
print("A.shape:", A.shape)
print("B.shape:", B.shape)
print("Diagonal:", diag1)

A.shape: (5, 5)
B.shape: (5, 5)
Diagonal from full dot: [0.93190702 1.00150965 0.56036218 0.81958385 1.57885243]

Non-square matrices:
A.shape: (5, 3)
B.shape: (3, 5)
Diagonal: [1.80564143 0.67872691 0.80030336 0.77588363 0.08302559]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [20]:
def interleave_zeros(v, num_zeros=3):
    """Interleave zeros between elements of vector."""
    n = len(v)
    # Create result array with zeros
    result = np.zeros(n + (n - 1) * num_zeros, dtype=v.dtype)
    # Place original elements at positions
    result[::(num_zeros + 1)] = v
    return result

v = np.array([1, 2, 3, 4, 5])
print("Original:", v)
print("With 3 zeros interleaved:", interleave_zeros(v, 3))

Original: [1 2 3 4 5]
With 3 zeros interleaved: [1 0 0 0 2 0 0 0 3 0 0 0 4 0 0 0 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [21]:
def multiply_3d_by_2d(A, B):
    """Multiply 3D array (5,5,3) by 2D array (5,5)."""
    # Method 1: Broadcasting
    return A * B[:, :, np.newaxis]

def multiply_3d_by_2d_einsum(A, B):
    """Using np.einsum."""
    return np.einsum('ijk,ij->ijk', A, B)

# Example
A = np.random.rand(5, 5, 3)
B = np.random.rand(5, 5)

result = multiply_3d_by_2d(A, B)
result_einsum = multiply_3d_by_2d_einsum(A, B)

print("A.shape:", A.shape)
print("B.shape:", B.shape)
print("Result shape:", result.shape)

# Check first slice
print("\nFirst slice of A:")
print(A[:, :, 0].round(3))
print("\nB:")
print(B.round(3))
print("\nResult first slice (broadcasting):")
print(result[:, :, 0].round(3))

print("\nUsing einsum result (first slice):")
print(result_einsum[:, :, 0].round(3))

print("\nMethods match:", np.allclose(result, result_einsum))

A.shape: (5, 5, 3)
B.shape: (5, 5)
Result shape: (5, 5, 3)

First slice of A:
[[0.234 0.24  0.031 0.63  0.289]
 [0.014 0.831 0.437 0.399 0.663]
 [0.045 0.074 0.267 0.576 0.828]
 [0.001 0.538 0.016 0.525 0.586]
 [0.437 0.821 0.388 0.482 0.999]]

B:
[[0.488 0.193 0.175 0.011 0.506]
 [0.264 0.28  0.233 0.871 0.704]
 [0.009 0.697 0.274 0.509 0.938]
 [0.539 0.685 0.386 0.132 0.107]
 [0.25  0.665 0.253 0.927 0.123]]

Result first slice (broadcasting):
[[0.114 0.046 0.005 0.007 0.146]
 [0.004 0.232 0.102 0.348 0.467]
 [0.    0.051 0.073 0.293 0.777]
 [0.    0.368 0.006 0.07  0.063]
 [0.109 0.546 0.098 0.447 0.123]]

Using einsum result (first slice):
[[0.114 0.046 0.005 0.007 0.146]
 [0.004 0.232 0.102 0.348 0.467]
 [0.    0.051 0.073 0.293 0.777]
 [0.    0.368 0.006 0.07  0.063]
 [0.109 0.546 0.098 0.447 0.123]]

Methods match: True


#### 72. How to swap two rows of an array? (★★★)

In [22]:
def swap_rows(arr, i, j):
    """Swap rows i and j in array."""
    arr[i], arr[j] = arr[j], arr[i].copy()
    return arr

def swap_columns(arr, i, j):
    """Swap columns i and j in array."""
    arr[:, i], arr[:, j] = arr[:, j], arr[:, i].copy()
    return arr

# Example with rows
arr = np.arange(12).reshape(4, 3)
print("Original array:")
print(arr)

# Swap rows 0 and 2
swap_rows(arr, 0, 2)
print("\nAfter swapping rows 0 and 2:")
print(arr)

# Using advanced indexing
arr2 = np.arange(12).reshape(4, 3)
arr2[[0, 2]] = arr2[[2, 0]]
print("\nUsing advanced indexing:")
print(arr2)

# Swap columns
arr3 = np.arange(12).reshape(4, 3)
print("\nOriginal for column swap:")
print(arr3)
swap_columns(arr3, 0, 2)
print("After swapping columns 0 and 2:")
print(arr3)

Original array:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

After swapping rows 0 and 2:
[[ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]
 [ 9 10 11]]

Using advanced indexing:
[[ 6  7  8]
 [ 3  4  5]
 [ 0  1  2]
 [ 9 10 11]]

Original for column swap:
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
After swapping columns 0 and 2:
[[ 2  1  0]
 [ 5  4  3]
 [ 8  7  6]
 [11 10  9]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [23]:
def unique_segments(triangles):
    edges = []
    for tri in triangles:
        edges.append(tuple(sorted([tri[0], tri[1]])))
        edges.append(tuple(sorted([tri[1], tri[2]])))
        edges.append(tuple(sorted([tri[2], tri[0]])))
    return np.unique(edges, axis=0)

vertices = np.random.randint(0, 20, size=(10, 3))
print("Triangles (vertex indices):")
print(vertices)

segments = unique_segments(vertices)
print(f"\nUnique line segments ({len(segments)}):")
print(segments)

all_vertices = np.unique(vertices)
print(f"\nAll vertices used: {all_vertices}")

def segment_counts(triangles):
    """Count how many triangles use each segment."""
    segments_list = []
    for tri in triangles:
        segments_list.extend([
            tuple(sorted([tri[0], tri[1]])),
            tuple(sorted([tri[1], tri[2]])),
            tuple(sorted([tri[2], tri[0]]))
        ])
    unique, counts = np.unique(segments_list, axis=0, return_counts=True)
    return unique, counts

unique, counts = segment_counts(vertices)
print("\nSegment usage counts:")
for seg, count in zip(unique, counts):
    print(f"{seg}: {count}")

Triangles (vertex indices):
[[12  5  2]
 [ 6  8  5]
 [16  2 14]
 [ 6  2 16]
 [ 6 11  5]
 [ 1 19  2]
 [ 1 15  5]
 [ 3  7  5]
 [11 17 16]
 [ 5  2 11]]

Unique line segments (26):
[[ 1  2]
 [ 1  5]
 [ 1 15]
 [ 1 19]
 [ 2  5]
 [ 2  6]
 [ 2 11]
 [ 2 12]
 [ 2 14]
 [ 2 16]
 [ 2 19]
 [ 3  5]
 [ 3  7]
 [ 5  6]
 [ 5  7]
 [ 5  8]
 [ 5 11]
 [ 5 12]
 [ 5 15]
 [ 6  8]
 [ 6 11]
 [ 6 16]
 [11 16]
 [11 17]
 [14 16]
 [16 17]]

All vertices used: [ 1  2  3  5  6  7  8 11 12 14 15 16 17 19]

Segment usage counts:
[1 2]: 1
[1 5]: 1
[ 1 15]: 1
[ 1 19]: 1
[2 5]: 2
[2 6]: 1
[ 2 11]: 1
[ 2 12]: 1
[ 2 14]: 1
[ 2 16]: 2
[ 2 19]: 1
[3 5]: 1
[3 7]: 1
[5 6]: 2
[5 7]: 1
[5 8]: 1
[ 5 11]: 2
[ 5 12]: 1
[ 5 15]: 1
[6 8]: 1
[ 6 11]: 1
[ 6 16]: 1
[11 16]: 1
[11 17]: 1
[14 16]: 1
[16 17]: 1


#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [24]:
def inverse_bincount(C):
    """Create array A such that np.bincount(A) == C."""
    A = np.repeat(np.arange(len(C)), C)
    return A

C = np.array([2, 3, 1, 4])  # Counts for values 0, 1, 2, 3
print("Counts C:", C)

A = inverse_bincount(C)
print("Array A:", A)
print("np.bincount(A):", np.bincount(A))
print("Matches:", np.array_equal(np.bincount(A), C))

# With longer array
C2 = np.array([1, 0, 3, 0, 2, 1])
A2 = inverse_bincount(C2)
print(f"\nC: {C2}")
print(f"A: {A2}")
print(f"np.bincount(A): {np.bincount(A2)}")

# Verify for random C
C_random = np.random.randint(0, 5, size=8)
A_random = inverse_bincount(C_random)
print(f"\nRandom C: {C_random}")
print(f"np.bincount(A): {np.bincount(A_random)}")
print("Matches:", np.array_equal(np.bincount(A_random), C_random))

Counts C: [2 3 1 4]
Array A: [0 0 1 1 1 2 3 3 3 3]
np.bincount(A): [2 3 1 4]
Matches: True

C: [1 0 3 0 2 1]
A: [0 2 2 2 4 4 5]
np.bincount(A): [1 0 3 0 2 1]

Random C: [1 3 3 4 3 0 2 1]
np.bincount(A): [1 3 3 4 3 0 2 1]
Matches: True


#### 75. How to compute averages using a sliding window over an array? (★★★)

In [25]:
def sliding_window_avg(arr, window_size):
    """Compute sliding window averages using np.convolve."""
    weights = np.ones(window_size) / window_size
    avg = np.convolve(arr, weights, mode='valid')
    return avg

def sliding_window_avg_strides(arr, window_size):
    """Sliding window average using strides."""
    shape = (arr.size - window_size + 1, window_size)
    strides = (arr.strides[0], arr.strides[0])
    windowed = np.lib.stride_tricks.as_strided(arr, shape=shape, strides=strides)
    return np.mean(windowed, axis=1)

def sliding_window_avg_cumsum(arr, window_size):
    """Sliding window average using cumulative sum."""
    cumsum = np.cumsum(np.concatenate([[0], arr]))
    return (cumsum[window_size:] - cumsum[:-window_size]) / window_size

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
window_size = 3

avg1 = sliding_window_avg(arr, window_size)
avg2 = sliding_window_avg_strides(arr, window_size)
avg3 = sliding_window_avg_cumsum(arr, window_size)

print("Array:", arr)
print(f"Sliding window average (window size {window_size}):")
print("Method 1 (convolve):", avg1.round(3))
print("Method 2 (strides):", avg2.round(3))
print("Method 3 (cumsum):", avg3.round(3))
print("All methods match:", np.allclose(avg1, avg2) and np.allclose(avg1, avg3))

# With larger window
window_size = 5
avg_large = sliding_window_avg(arr, window_size)
print(f"\nWindow size {window_size}:", avg_large)

Array: [ 1  2  3  4  5  6  7  8  9 10]
Sliding window average (window size 3):
Method 1 (convolve): [2. 3. 4. 5. 6. 7. 8. 9.]
Method 2 (strides): [2. 3. 4. 5. 6. 7. 8. 9.]
Method 3 (cumsum): [2. 3. 4. 5. 6. 7. 8. 9.]
All methods match: True

Window size 5: [3. 4. 5. 6. 7. 8.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

In [26]:
def shift_2d_from_1d(Z, window_size):
    """Build 2D array where each row is shifted version of 1D array."""
    n = len(Z) - window_size + 1
    result = np.zeros((n, window_size))
    
    for i in range(n):
        result[i] = Z[i:i+window_size]
    
    return result

def shift_2d_from_1d_strides(Z, window_size):
    """Using strides for efficiency."""
    n = len(Z) - window_size + 1
    shape = (n, window_size)
    strides = (Z.strides[0], Z.strides[0])
    return np.lib.stride_tricks.as_strided(Z, shape=shape, strides=strides)

Z = np.arange(1, 15)
window_size = 4

result = shift_2d_from_1d(Z, window_size)
result_strides = shift_2d_from_1d_strides(Z, window_size)

print("Z:", Z)
print(f"\nResult (each row shifted by 1, window_size={window_size}):")
print(result)

print("\nUsing strides:")
print(result_strides)

# Check last row
print(f"\nLast row: {result[-1]}")
print(f"Expected: {Z[-window_size:]}")

# With different window size
window_size = 3
result3 = shift_2d_from_1d(Z, window_size)
print(f"\nWindow size {window_size}:")
print(result3)

Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Result (each row shifted by 1, window_size=4):
[[ 1.  2.  3.  4.]
 [ 2.  3.  4.  5.]
 [ 3.  4.  5.  6.]
 [ 4.  5.  6.  7.]
 [ 5.  6.  7.  8.]
 [ 6.  7.  8.  9.]
 [ 7.  8.  9. 10.]
 [ 8.  9. 10. 11.]
 [ 9. 10. 11. 12.]
 [10. 11. 12. 13.]
 [11. 12. 13. 14.]]

Using strides:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]

Last row: [11. 12. 13. 14.]
Expected: [11 12 13 14]

Window size 3:
[[ 1.  2.  3.]
 [ 2.  3.  4.]
 [ 3.  4.  5.]
 [ 4.  5.  6.]
 [ 5.  6.  7.]
 [ 6.  7.  8.]
 [ 7.  8.  9.]
 [ 8.  9. 10.]
 [ 9. 10. 11.]
 [10. 11. 12.]
 [11. 12. 13.]
 [12. 13. 14.]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [27]:
# Boolean negation in-place
bool_arr = np.array([True, False, True, False, True])
print("Original boolean array:", bool_arr)

# In-place negation using np.logical_not
np.logical_not(bool_arr, out=bool_arr)
print("After in-place negation:", bool_arr)

# For floats, change sign in-place
float_arr = np.array([-1.5, 2.3, -3.7, 4.1, -5.2])
print("\nOriginal float array:", float_arr)

# Method 1: Using np.negative
np.negative(float_arr, out=float_arr)
print("After in-place sign change:", float_arr)

# Method 2: Direct multiplication
float_arr2 = np.array([-1.5, 2.3, -3.7, 4.1, -5.2])
float_arr2 *= -1
print("\nUsing multiplication:", float_arr2)

# For integers
int_arr = np.array([-1, 2, -3, 4, -5])
np.negative(int_arr, out=int_arr)
print("\nInteger array after sign change:", int_arr)

# Conditional sign change (only positive to negative)
arr = np.array([-1, 2, 3, -4, 5])
positive_mask = arr > 0
arr[positive_mask] = -arr[positive_mask]
print("\nOnly positive to negative:", arr)

Original boolean array: [ True False  True False  True]
After in-place negation: [False  True False  True False]

Original float array: [-1.5  2.3 -3.7  4.1 -5.2]
After in-place sign change: [ 1.5 -2.3  3.7 -4.1  5.2]

Using multiplication: [ 1.5 -2.3  3.7 -4.1  5.2]

Integer array after sign change: [ 1 -2  3 -4  5]

Only positive to negative: [-1 -2 -3 -4 -5]


#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

In [28]:
def distance_point_to_lines(P0, P1, p):
    """
    Compute distance from point p to each line defined by (P0[i], P1[i]).
    Lines are 2D.
    """
    # Vector from P0 to P1
    v = P1 - P0
    # Vector from P0 to p
    w = p - P0
    
    # Projection parameter t = (w·v) / (v·v)
    v_dot_v = np.sum(v * v, axis=1)
    t = np.sum(w * v, axis=1) / v_dot_v
    
    # Clamp t to [0, 1] for line segment (not infinite line)
    t = np.clip(t, 0, 1)
    
    # Closest point on line segment
    closest = P0 + t[:, np.newaxis] * v
    
    # Distance from p to closest point
    distance = np.sqrt(np.sum((p - closest) ** 2, axis=1))
    return distance, closest

# Example
P0 = np.array([[0, 0], [1, 2], [2, 3]])
P1 = np.array([[2, 2], [3, 4], [4, 5]])
p = np.array([3, 1])

print("Line start points (P0):")
print(P0)
print("\nLine end points (P1):")
print(P1)
print(f"\nPoint p: {p}")

distances, closest_points = distance_point_to_lines(P0, P1, p)
print("\nDistances to each line:", distances.round(3))
print("\nClosest points on each line:")
print(closest_points)

# For infinite lines (without clamping)
def distance_point_to_infinite_lines(P0, P1, p):
    v = P1 - P0
    w = p - P0
    v_dot_v = np.sum(v * v, axis=1)
    t = np.sum(w * v, axis=1) / v_dot_v
    closest = P0 + t[:, np.newaxis] * v
    distance = np.sqrt(np.sum((p - closest) ** 2, axis=1))
    return distance, closest

dist_inf, _ = distance_point_to_infinite_lines(P0, P1, p)
print("\nDistances to infinite lines:", dist_inf.round(3))

Line start points (P0):
[[0 0]
 [1 2]
 [2 3]]

Line end points (P1):
[[2 2]
 [3 4]
 [4 5]]

Point p: [3 1]

Distances to each line: [1.414 2.121 2.236]

Closest points on each line:
[[2.  2. ]
 [1.5 2.5]
 [2.  3. ]]

Distances to infinite lines: [1.414 2.121 2.121]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

In [29]:
def distance_points_to_lines(P0, P1, P):
    """
    Compute distance from each point P[j] to each line defined by (P0[i], P1[i]).
    Returns matrix of shape (len(P), len(P0)).
    """
    n_lines = len(P0)
    n_points = len(P)
    
    # Vector for each line
    v = P1 - P0  # shape (n_lines, 2)
    v_dot_v = np.sum(v * v, axis=1)  # shape (n_lines,)
    
    # For each point, compute distance to each line
    distances = np.zeros((n_points, n_lines))
    
    for j, point in enumerate(P):
        w = point - P0  # shape (n_lines, 2)
        t = np.sum(w * v, axis=1) / v_dot_v  # shape (n_lines,)
        t = np.clip(t, 0, 1)
        closest = P0 + t[:, np.newaxis] * v
        distances[j] = np.sqrt(np.sum((point - closest) ** 2, axis=1))
    
    return distances

# Example
P0 = np.array([[0, 0], [1, 0], [0, 1]])
P1 = np.array([[2, 0], [3, 1], [1, 2]])
P = np.array([[1, 1], [2, 2], [0, 0], [3, 0]])

print("Line start points (P0):")
print(P0)
print("\nLine end points (P1):")
print(P1)
print("\nPoints (P):")
print(P)

distances = distance_points_to_lines(P0, P1, P)
print("\nDistance matrix (points × lines):")
print(distances.round(3))

# For infinite lines
def distance_points_to_infinite_lines(P0, P1, P):
    n_lines = len(P0)
    n_points = len(P)
    
    v = P1 - P0
    v_dot_v = np.sum(v * v, axis=1)
    
    distances = np.zeros((n_points, n_lines))
    
    for j, point in enumerate(P):
        w = point - P0
        t = np.sum(w * v, axis=1) / v_dot_v
        closest = P0 + t[:, np.newaxis] * v
        distances[j] = np.sqrt(np.sum((point - closest) ** 2, axis=1))
    
    return distances

dist_inf = distance_points_to_infinite_lines(P0, P1, P)
print("\nDistance matrix (infinite lines):")
print(dist_inf.round(3))

Line start points (P0):
[[0 0]
 [1 0]
 [0 1]]

Line end points (P1):
[[2 0]
 [3 1]
 [1 2]]

Points (P):
[[1 1]
 [2 2]
 [0 0]
 [3 0]]

Distance matrix (points × lines):
[[1.    0.894 0.707]
 [2.    1.342 1.   ]
 [0.    1.    1.   ]
 [1.    0.894 2.828]]

Distance matrix (infinite lines):
[[1.    0.894 0.707]
 [2.    1.342 0.707]
 [0.    0.447 0.707]
 [0.    0.894 2.828]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [30]:
def extract_centered(arr, center, shape, fill_value=0):
    """
    Extract subpart of arr with given shape centered on center.
    Pad with fill_value when necessary.
    """
    # Get array dimensions
    arr_shape = arr.shape
    
    # Calculate start and end indices
    start = np.array(center) - np.array(shape) // 2
    end = start + np.array(shape)
    
    # Calculate slices for extraction
    slices = []
    paddings = []
    
    for i in range(len(arr_shape)):
        # Adjust for odd shapes
        if shape[i] % 2 == 0:
            start[i] += 1
        
        # Calculate padding needed
        pad_before = max(0, -start[i])
        pad_after = max(0, end[i] - arr_shape[i])
        
        # Clip indices to array bounds
        slice_start = max(0, start[i])
        slice_end = min(arr_shape[i], end[i])
        
        slices.append(slice(slice_start, slice_end))
        paddings.append((pad_before, pad_after))
    
    # Extract subarray
    subarr = arr[tuple(slices)]
    
    # Pad if necessary
    if any(sum(pad) > 0 for pad in paddings):
        subarr = np.pad(subarr, paddings, mode='constant', constant_values=fill_value)
    
    return subarr

# Example with 2D array
arr_2d = np.arange(25).reshape(5, 5)
print("Original array:")
print(arr_2d)

center = (2, 2)
shape = (4, 4)
extracted = extract_centered(arr_2d, center, shape, fill_value=-1)
print(f"\nExtracted {shape} centered at {center} (pad with -1):")
print(extracted)

# Example at edge
center = (0, 4)
shape = (3, 3)
extracted_edge = extract_centered(arr_2d, center, shape, fill_value=-1)
print(f"\nExtracted {shape} centered at {center} (pad with -1):")
print(extracted_edge)

# 3D example
arr_3d = np.arange(27).reshape(3, 3, 3)
center = (1, 1, 1)
shape = (2, 2, 2)
extracted_3d = extract_centered(arr_3d, center, shape, fill_value=-1)
print(f"\n3D array shape: {arr_3d.shape}")
print(f"Extracted {shape} centered at {center}:")
print(extracted_3d)

Original array:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Extracted (4, 4) centered at (2, 2) (pad with -1):
[[ 6  7  8]
 [11 12 13]
 [16 17 18]]

Extracted (3, 3) centered at (0, 4) (pad with -1):
[[-1 -1 -1]
 [ 3  4 -1]
 [ 8  9 -1]]

3D array shape: (3, 3, 3)
Extracted (2, 2, 2) centered at (1, 1, 1):
[[[13]]]


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [31]:
def sliding_windows(Z, window_size):
    """Generate sliding windows from array Z."""
    # Method 1: Using np.lib.stride_tricks.sliding_window_view (NumPy 1.20+)
    try:
        from numpy.lib.stride_tricks import sliding_window_view
        return sliding_window_view(Z, window_shape=window_size)
    except ImportError:
        pass
    
    # Method 2: Manual implementation
    n = len(Z) - window_size + 1
    result = np.zeros((n, window_size), dtype=Z.dtype)
    for i in range(n):
        result[i] = Z[i:i+window_size]
    return result

Z = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14])
window_size = 4

R = sliding_windows(Z, window_size)
print("Z:", Z)
print(f"\nSliding windows (size {window_size}):")
print(R)

# Alternative using broadcasting
def sliding_windows_broadcast(Z, window_size):
    n = len(Z) - window_size + 1
    indices = np.arange(window_size)[np.newaxis, :] + np.arange(n)[:, np.newaxis]
    return Z[indices]

R_broadcast = sliding_windows_broadcast(Z, window_size)
print("\nUsing broadcasting:")
print(R_broadcast)

# Different window sizes
print("\nWindow size 3:")
print(sliding_windows(Z, 3))

Z: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

Sliding windows (size 4):
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]

Using broadcasting:
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]

Window size 3:
[[ 1  2  3]
 [ 2  3  4]
 [ 3  4  5]
 [ 4  5  6]
 [ 5  6  7]
 [ 6  7  8]
 [ 7  8  9]
 [ 8  9 10]
 [ 9 10 11]
 [10 11 12]
 [11 12 13]
 [12 13 14]]


#### 82. Compute a matrix rank (★★★)

In [ ]:
def matrix_rank(A, tol=None):
    u, s, vh = np.linalg.svd(A, full_matrices=False)
    
    if tol is None:
        tol = s.max() * max(A.shape) * np.finfo(s.dtype).eps
    
    rank = np.sum(s > tol)
    return rank, s

# Examples
A1 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])  # rank 2
rank1, s1 = matrix_rank(A1)
print("Matrix A1:")
print(A1)
print(f"Rank: {rank1}")
print(f"Singular values: {s1.round(4)}")

A2 = np.eye(5)  # rank 5
rank2, s2 = matrix_rank(A2)
print("\nMatrix A2 (identity 5x5):")
print(f"Rank: {rank2}")
print(f"Singular values: {s2.round(4)}")

A3 = np.array([[1, 0, 0], [0, 0, 0], [0, 0, 0]])  # rank 1
rank3, s3 = matrix_rank(A3)
print("\nMatrix A3:")
print(A3)
print(f"Rank: {rank3}")

# Using numpy's built-in rank
print(f"\nNumPy's built-in rank (A1): {np.linalg.matrix_rank(A1)}")
print(f"NumPy's built-in rank (A2): {np.linalg.matrix_rank(A2)}")

Matrix A1:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Rank: 2
Singular values: [16.8481  1.0684  0.    ]

Matrix A2 (identity 5x5):
Rank: 5
Singular values: [1. 1. 1. 1. 1.]

Matrix A3:
[[1 0 0]
 [0 0 0]
 [0 0 0]]
Rank: 1

NumPy's built-in rank (A1): 2
NumPy's built-in rank (A2): 5


#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)