# Numpy Exercise 2

### All of the questions in this exercise are attributed to rougier/numpy-100

In [1]:
import numpy as np

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [3]:
# Create a sample array
arr = np.ones((3, 3))
print("Original array:")
print(arr)

# Add border of zeros using np.pad
padded = np.pad(arr, pad_width=1, mode='constant', constant_values=0)
print("\nArray with border:")
print(padded)

Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

Array with border:
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [5]:
print("0 * np.nan =", 0 * np.nan)              
print("np.nan == np.nan =", np.nan == np.nan) 
print("np.inf > np.nan =", np.inf > np.nan)    
print("np.nan - np.nan =", np.nan - np.nan) 
print("np.nan in set([np.nan]) =", np.nan in set([np.nan]))
print("0.3 == 3 * 0.1 =", 0.3 == 3 * 0.1)

0 * np.nan = nan
np.nan == np.nan = False
np.inf > np.nan = False
np.nan - np.nan = nan
np.nan in set([np.nan]) = True
0.3 == 3 * 0.1 = False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [6]:
# Create 5x5 matrix with zeros
matrix = np.zeros((5, 5), dtype=int)

# Fill values just below the diagonal
for i in range(1, 5):
    matrix[i, i-1] = i

print("Matrix with values below diagonal:")
print(matrix)

Matrix with values below diagonal:
[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1

print("Checkerboard pattern:")
print(checkerboard)

Checkerboard pattern:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [8]:
shape = (6, 7, 8)
index_100 = np.unravel_index(99, shape)
print(f"Index of the 100th element in shape {shape}: {index_100}")

arr = np.arange(np.prod(shape)).reshape(shape)
print(f"Value at index {index_100}: {arr[index_100]}")

Index of the 100th element in shape (6, 7, 8): (np.int64(1), np.int64(5), np.int64(3))
Value at index (np.int64(1), np.int64(5), np.int64(3)): 99


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [9]:
# Create a 2x2 base pattern
base = np.array([[0, 1], [1, 0]])
checkerboard_tile = np.tile(base, (4, 4))

print("Checkerboard using tile function:")
print(checkerboard_tile)

Checkerboard using tile function:
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [10]:
# Create random 5x5 matrix
random_matrix = np.random.rand(5, 5)
print("Original random matrix:")
print(random_matrix)

# Z-score normalization: (x - mean) / std
normalized = (random_matrix - np.mean(random_matrix)) / np.std(random_matrix)
print("\nZ-score normalized matrix:")
print(normalized)

# Min-max normalization
min_max_normalized = (random_matrix - np.min(random_matrix)) / (np.max(random_matrix) - np.min(random_matrix))
print("\nMin-Max normalized:")
print(min_max_normalized)

Original random matrix:
[[0.40443386 0.35920998 0.03415671 0.87194006 0.7484823 ]
 [0.4187432  0.65275574 0.1376734  0.35742818 0.53748689]
 [0.62120145 0.96352183 0.72117575 0.01268829 0.17048122]
 [0.57229187 0.31890589 0.99543317 0.50254022 0.82935302]
 [0.34718058 0.18987783 0.00102516 0.05881877 0.98803421]]

Z-score normalized matrix:
[[-0.21871179 -0.36382677 -1.40686182  1.28142808  0.88527524]
 [-0.17279579  0.57810663 -1.07469617 -0.36954422  0.20823046]
 [ 0.47685483  1.57529683  0.79765363 -1.47574996 -0.96942201]
 [ 0.31991314 -0.49315504  1.67769434  0.09609316  1.14477422]
 [-0.40242686 -0.90718191 -1.51317477 -1.32772589  1.65395246]]

Min-Max normalized:
[[0.40567724 0.36019904 0.03331787 0.87581244 0.75166042]
 [0.42006705 0.65539555 0.13741667 0.35840723 0.53947848]
 [0.62366382 0.96790921 0.72420031 0.01172872 0.17040898]
 [0.57447919 0.31966831 1.         0.5043353  0.8329859 ]
 [0.348102   0.18991467 0.         0.05811861 0.99255943]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [11]:
# Define custom dtype
rgba_dtype = np.dtype([('r', np.uint8), ('g', np.uint8), ('b', np.uint8), ('a', np.uint8)])

# Create an array with this dtype
color_array = np.array([(255, 0, 0, 255), (0, 255, 0, 128), (0, 0, 255, 200)], dtype=rgba_dtype)
print("RGBA color array:")
print(color_array)
print("\nAccessing individual components:")
print("Red:", color_array['r'])
print("Green:", color_array['g'])
print("Blue:", color_array['b'])
print("Alpha:", color_array['a'])

RGBA color array:
[(255,   0,   0, 255) (  0, 255,   0, 128) (  0,   0, 255, 200)]

Accessing individual components:
Red: [255   0   0]
Green: [  0 255   0]
Blue: [  0   0 255]
Alpha: [255 128 200]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [12]:
# Create matrices
A = np.random.rand(5, 3)
B = np.random.rand(3, 2)

# Matrix multiplication using np.dot
C = np.dot(A, B)
# Or using @ operator
C2 = A @ B

print("Matrix A shape:", A.shape)
print("Matrix B shape:", B.shape)
print("Result C shape:", C.shape)
print("\nResult C:")
print(C)
print("\nUsing @ operator:")
print(C2)

Matrix A shape: (5, 3)
Matrix B shape: (3, 2)
Result C shape: (5, 2)

Result C:
[[0.28980412 0.59388344]
 [0.67948637 0.67810998]
 [0.25651099 0.37673255]
 [0.67939486 1.11459721]
 [0.48048017 0.50392803]]

Using @ operator:
[[0.28980412 0.59388344]
 [0.67948637 0.67810998]
 [0.25651099 0.37673255]
 [0.67939486 1.11459721]
 [0.48048017 0.50392803]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [13]:
# Create 1D array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print("Original array:", arr)

# Negate elements between 3 and 8 (inclusive)
mask = (arr >= 3) & (arr <= 8)
arr[mask] = -arr[mask]
print("Modified array:", arr)

Original array: [ 1  2  3  4  5  6  7  8  9 10]
Modified array: [ 1  2 -3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [14]:
# Part 1: Python's built-in sum
print("Python sum(range(5), -1):", sum(range(5), -1))  # sum(0,1,2,3,4) - 1 = 9

# Part 2: NumPy's sum
import numpy as np
print("NumPy sum(range(5), -1):", np.sum(range(5), -1))

Python sum(range(5), -1): 9
NumPy sum(range(5), -1): 10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [15]:
Z = np.array([1, 2, 3, 4, 5], dtype=int)

print("Z =", Z)
print("\nZ**Z:", Z**Z)                    # Legal - exponentiation
print("2 << Z >> 2:", 2 << Z >> 2)        # Legal - bitwise operations
print("Z <- Z:", Z < -Z)                  # Legal - comparison
print("1j*Z:", 1j * Z)                    # Legal - complex multiplication
print("Z/1/1:", Z / 1 / 1)                # Legal - division

try:
    print("Z<Z>Z:", Z < Z > Z)
except ValueError as e:
    print("\nZ<Z>Z is illegal:", e)

Z = [1 2 3 4 5]

Z**Z: [   1    4   27  256 3125]
2 << Z >> 2: [ 1  2  4  8 16]
Z <- Z: [False False False False False]
1j*Z: [0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j]
Z/1/1: [1. 2. 3. 4. 5.]

Z<Z>Z is illegal: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [17]:
print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
print("np.array([np.nan]).astype(int).astype(float):", 
      np.array([np.nan]).astype(int).astype(float))

np.array(0) / np.array(0): nan
np.array(0) // np.array(0): 0
np.array([np.nan]).astype(int).astype(float): [0.]


/var/folders/2y/rw1f6sdn1_z84ny_s3mlv_1w0000gn/T/ipykernel_63325/2540929026.py:1: RuntimeWarning: invalid value encountered in divide
  print("np.array(0) / np.array(0):", np.array(0) / np.array(0))
/var/folders/2y/rw1f6sdn1_z84ny_s3mlv_1w0000gn/T/ipykernel_63325/2540929026.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print("np.array(0) // np.array(0):", np.array(0) // np.array(0))
/var/folders/2y/rw1f6sdn1_z84ny_s3mlv_1w0000gn/T/ipykernel_63325/2540929026.py:4: RuntimeWarning: invalid value encountered in cast
  np.array([np.nan]).astype(int).astype(float))


#### 29. How to round away from zero a float array ? (★☆☆)

In [18]:
def round_away_from_zero(arr):
    """Round numbers away from zero."""
    # For positive numbers, ceil; for negative numbers, floor
    return np.copysign(np.ceil(np.abs(arr)), arr)

def round_away_from_zero2(arr):
    """Alternative method using np.where."""
    return np.where(arr >= 0, np.ceil(arr), np.floor(arr))

arr = np.array([-2.3, -1.7, -0.5, 0.5, 1.7, 2.3])
print("Original:", arr)
print("Round away from zero:", round_away_from_zero(arr))
print("Alternative:", round_away_from_zero2(arr))

Original: [-2.3 -1.7 -0.5  0.5  1.7  2.3]
Round away from zero: [-3. -2. -1.  1.  2.  3.]
Alternative: [-3. -2. -1.  1.  2.  3.]


#### 30. How to find common values between two arrays? (★☆☆)

In [19]:
A = np.array([1, 2, 3, 4, 5, 6])
B = np.array([4, 5, 6, 7, 8, 9])

common = np.intersect1d(A, B)
print("Array A:", A)
print("Array B:", B)
print("Common values:", common)

# With duplicates
A2 = np.array([1, 2, 2, 3, 4])
B2 = np.array([2, 3, 3, 4, 5])
common2 = np.intersect1d(A2, B2)
print("\nWith duplicates:")
print("A:", A2)
print("B:", B2)
print("Common values:", common2)

Array A: [1 2 3 4 5 6]
Array B: [4 5 6 7 8 9]
Common values: [4 5 6]

With duplicates:
A: [1 2 2 3 4]
B: [2 3 3 4 5]
Common values: [2 3 4]
